### ISSUE TITLE
Screenshot is stretched in UI

### ISSUE THREAD

**Issue by machawk1** [erikaris/web-memento-damage#11]
The image shown in the screenshots tab is horizontally stretched to fit the space, making the image look odd.

![screen shot 2017-03-25 at 1 32 33 pm](https://cloud.githubusercontent.com/assets/2514780/24324595/8a9318c0-115f-11e7-98f8-d29ad515b5c9.png)

Overlaying the stretched version over the original image in Photoshop makes this more apparent:

![delta](https://cloud.githubusercontent.com/assets/2514780/24324615/edf54f96-115f-11e7-8b46-6de4ece8b7ac.png)

**Comment by erikaris** [comment]
Yes, the size of the screenshot is set to adjust to the container size to avoid scrolling. I still use the original size to calculate the damage. 
The screenshot provided in the tab 'screenshot' here is to just give the user a `glance` about how the page looks like. I could show the original size for the image in tab `screenshot', but it would be less aesthetic (I think) since it's bigger than the container size.
