### ISSUE TITLE
Damage of (uri) clipped

### ISSUE THREAD

**Issue by machawk1** [erikaris/web-memento-damage#9]
The title "Damage of http://matkelly.com" is visually clipped. Note in the attached how the bottom of the "g" in "Damage" is cut off.

Chrome 57, macOS 10.12.3
![screen shot 2017-03-25 at 1 23 46 pm](https://cloud.githubusercontent.com/assets/2514780/24324519/6f2916bc-115e-11e7-86fd-bffc4caa4f2f.png)

**Comment by machawk1** [comment]
Just noticing that @ibnesayeed already mentioned this via e-mail. Above is a graphical representation of what he described.

**Comment by ibnesayeed** [comment]
Also, there are a couple things to note in the screenshot:

* Due to the error there was no calculation time available, but the info block still appears saying, "Info Calculation is finished in seconds."
* The error message says, "Error! URI must be in HTML format. See log tab", it is not clear to me what is means for a URI to be in HTML format? Are you referring to the content-type of the resource to be HTML or the URL needs to be URL-Encoded?

**Comment by machawk1** [comment]
@ibnesayeed I documented this more in #10

**Comment by erikaris** [comment]
I already fixed it in accordance with the feedback, thank you. 

> The error message says, "Error! URI must be in HTML format. See log tab", it is not clear to me what is means for a URI to be in HTML format? Are you referring to the content-type of the resource to be HTML or the URL needs to be URL-Encoded?

I am referring to the content-type of URI-M. I modified the error message with this: "Error! This is not an HTML page. See log tab". 
Hopefully, this error message is clear and unambiguous.
